---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "cobalt"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::hmftools-cobalt=1.16"
