---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "hmftoolspurple"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::hmftools-purple=4.0.2"
